### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by racinmat** [andhus/dirhash-python#18]
on windows, the library is not working with `scantree`=0.0.2, would it be possible to use some more platform-independent library?

**Comment by frichtarik** [comment]
Hi @racinmat, thanks for the report. 
Could you please add more info ? Windows version, expected vs actual behavior, ... anything can help :) thanks in advance

**Comment by racinmat** [comment]
Hi, sure, sorry, I had a typo in the package name, I meant [scantree](https://github.com/andhus/scantree). There is open issue since 2020 https://github.com/andhus/scantree/issues/4 which describes that its newer release broke the functionality on windows.

**Comment by frichtarik** [comment]
Hi @racinmat  
I've created new PR to fix the windows issue https://github.com/andhus/scantree/pull/22 
If you're interested, you can test the fix the commit even before it gets merged 

instead of `pip install dirhash` 
use `pip install dirhash git+https://github.com/frichtarik/scantree.git@8b641db`
when preparing the environment

**Comment by racinmat** [comment]
Works for me, thanks!

**Comment by andhus** [comment]
Should be fixed here https://github.com/andhus/dirhash-python/pull/29

**Comment by andhus** [comment]
Let me know it there are any issues still after https://github.com/andhus/dirhash-python/releases/tag/v0.5.0 👍
